version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./internal/db/migrations:/migrations
    ports:
      - "5444:5432"

  migrate:
    image: migrate/migrate:v4.15.2
    command: ["-path", "/migrations", "-database", "${DATABASE_URL}", "up"]
    env_file:
      - .env
    volumes:
      - ./internal/db/migrations:/migrations
    depends_on:
      - db

  web:
    build: .
    depends_on:
      - db
      - migrate
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: ["/subscriptions"]

volumes:
  db_data:
